version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
      QUEUE_NAME: projqueue
    ports:
      - 5672:5672
      - 15672:15672
  consumer:
    build: .
    environment:
      QUEUE_NAME: ${QUEUE_NAME}   # reference to the environment variable
    ports:
      - 8087:8087
    depends_on:
      - rabbitmq
