apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spring-consumer
spec:
  scaleTargetRef:
    name: consumer-deployment
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: rabbitmq
      metadata:
        queueName: projqueue
        host: amqp://guest:guest@172.17.0.2:5672
        mode: QueueLength
        port: "5672"
        username: guest
        password: guest
        value: "6"
    - type: rabbitmq
      metadata:
        queueName: healthqueue
        host: amqp://guest:guest@172.17.0.2:5672
        mode: QueueLength
        port: "5672"
        username: guest
        password: guest
        value: "1"







