apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-container
          image: elnalouti/sigrepo:tagname
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_RABBITMQ_HOST
              value: 172.17.0.2
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: SPRING_RABBITMQ_VIRTUAL_HOST
              value: /
---
apiVersion: v1
kind: Service
metadata:
  name: spring-consumer-service
spec:
  selector:
    app: consumer-app
  ports:
    - name: http
      port: 8087
      targetPort: 8087
  type: LoadBalancer
