apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv  # Replace with a unique name for the PV
spec:
  capacity:
    storage: 5Gi  # Replace with the desired storage capacity
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Modify this based on your requirements (e.g., ReadWriteMany for multiple pods)
  persistentVolumeReclaimPolicy: Retain  # Retain will preserve the data after PVC is deleted
  storageClassName: manual
  hostPath:
    path: "C:\\Users\\HP\\Desktop\\fold\\dataset.arff"  # Replace with the path on your host machine where the data should be stored

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc  # Replace with a unique name for the PVC
spec:
  accessModes:
    - ReadWriteOnce  # Modify this based on your requirements (e.g., ReadWriteMany for multiple pods)
  resources:
    requests:
      storage: 1Gi  # Replace with the desired storage capacity, should be less than or equal to PV's capacity

