apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce  # This means the volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # This retains the data even if the PersistentVolumeClaim is deleted
  hostPath:
    path: "C:/Users/HP/Desktop/fold/dataset.arff"  # This is the host path where the data will be stored on the node
