apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  host: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=     # base64-encoded "localhost"
  username: Z3Vlc3Q=     # base64-encoded "guest"
  password: Z3Vlc3Q=     # base64-encoded "guest"
